/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IncrementorInterface extends ethers.utils.Interface {
  functions: {
    "incrementX(uint256)": FunctionFragment;
    "incrementY(uint256)": FunctionFragment;
    "incrementZ(uint256)": FunctionFragment;
    "incrementaddress()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "incrementX",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementY",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementZ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementaddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "incrementX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "incrementY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "incrementZ", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incrementaddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class Incrementor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IncrementorInterface;

  functions: {
    incrementX(
      _x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    incrementY(
      _y: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    incrementZ(
      _z: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    incrementaddress(overrides?: CallOverrides): Promise<[string]>;
  };

  incrementX(
    _x: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  incrementY(
    _y: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  incrementZ(
    _z: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  incrementaddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    incrementX(_x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    incrementY(_y: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    incrementZ(_z: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    incrementaddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    incrementX(
      _x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    incrementY(
      _y: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    incrementZ(
      _z: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    incrementaddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    incrementX(
      _x: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    incrementY(
      _y: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    incrementZ(
      _z: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    incrementaddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
